# Generated by Django 3.0.7 on 2020-07-08 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('idp', models.CharField(max_length=9, primary_key='True', serialize=False)),
                ('real_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tz', models.CharField(max_length=50)),
                ('activity_periods', models.CharField(max_length=25)),
                ('idp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsontestapp.Users')),
            ],
        ),
    ]
